    public static void youDoThisPart() {
        /*Your assignment is to write two comments below this one.  They should describe the few lines of code you se below.
		Simply describe what the code is doing based on what you learned from readings and in class.
        Make one as a single line comment using the // notation.  Make the other one a multi line comment using the /* notation.
        When you're done, save this file so that it is compiled and stored in Salesforce.  */

        /*Declare an integer variable named i 
         set an initial value of 2*/
		Integer i;
		i = 2;

        //Declare a string variable named s and set the initial value to My String
		String s = 'My String';

    }
